### ISSUE TITLE
open is not working on ios

### ISSUE THREAD

**Issue by sibelius** [pandiaraj44/react-native-datepicker-dialog#1]
I've tried to use this library on RN42 and `open` will not working on iOS.

I haven't tested on android yet

**Comment by pandiarajan-i2i** [comment]
Hi  Sibelius,
We will check it and let you know!

**Comment by pandiaraj44** [comment]
Hi  Sibelius,
We will check it and let you know!

**Comment by theboulderking** [comment]
Ran into the same issue, any update? From my debugging it seems to be related to the assignment of the refs.

**Comment by pandiaraj44** [comment]
Hi, @mattathias Have you tried out the example?
When opening the datepicker dialog you need to pass the date object. If you didn't then datepicker will not be shown.

```
this.refs.dobDialog.open({
      date: new Date(), //Any date
});
```

**Comment by theboulderking** [comment]
Yes I did, I followed the example exactly

**Comment by pandiaraj44** [comment]
@mattathias Can you please send us the error logs?

**Comment by pandiaraj44** [comment]
Hi, @mattathias

Please let us know if you are still facing the same issue. We need more info on how you handled the onPress event of the date picker.

As for now, I'm going to close this issue.

You may reopen this issue at any time.
