### ISSUE TITLE
'OK' and 'CANCEL' buttons on dialog appear empty

### ISSUE THREAD

**Issue by JorgeAlonso** [pandiaraj44/react-native-datepicker-dialog#13]
Hi!

I have started using this component on a new react native development, but unfortunately, when the dialog is displayed (on iOS emulator), the 'ok' and 'cancel' buttons appear empty. They are clickable, but no text is displayed on them.

Any hint on what could be happening? I have not found how to define the text on those buttons.

Thanks

**Comment by kf729ik** [comment]
Any solution? I have the same problem on IOS.

**Comment by Nemesisesq** [comment]
Set the props "okLabel" and "cancelLabel" on the DatePickerDialog component tag.

**Comment by pandiaraj44** [comment]
Thanks, @Nemesisesq .

Hi @JorgeAlonso , @kf729ik ,

As for now, you need to pass the label name. We will add default props in next release.

**Comment by Krupatank** [comment]
update  this  
 <DatePickerDialog ref="dobDialog" **okLabel = 'OK' cancelLabel = 'CANCEL'** onDatePicked={this.onDOBDatePicked.bind(this)} />

**Comment by pandiaraj44** [comment]
Thanks, @Krupatank ,

Hi @JorgeAlonso , @kf729ik 
Ios datepicker-dialog ok, cancel button label added to default props. If you didn't give "okLablel/cancelLabel" then default label(Ok/Cancel will be shown.


New version released.
https://www.npmjs.com/package/react-native-datepicker-dialog

**Comment by JorgeAlonso** [comment]
Awesome, thanks a lot for the prompt response
