### ISSUE TITLE
How to set locale?

### ISSUE THREAD

**Issue by marcoizzo** [pandiaraj44/react-native-datepicker-dialog#15]

**Comment by Tamiyadd** [comment]
@marcoizzo you can use my pull request to add IOS locale (android use system locale)
https://github.com/pandiaraj44/react-native-datepicker-dialog/pull/16

**Comment by pandiaraj44** [comment]
Thanks, @Tamiyadd ,

Hi @marcoizzo ,
The locale option has been added and published on the npm.

New version released.
https://www.npmjs.com/package/react-native-datepicker-dialog

**Comment by marcoizzo** [comment]
Thanks!
