### ISSUE TITLE
onCancel isn't being called on iOS

### ISSUE THREAD

**Issue by diegocouto** [pandiaraj44/react-native-datepicker-dialog#2]
Hi, guys!

First of all, congratulations for your great work! We've been using react-native-datepicker-dialog for a while without any problems.

Recently, we noticed that the `onCancel` handler works like a charm on Android, but it isn't being called on iOS.

**Versions**

* react-native - 0.43.3
* react-native-datepicker-dialog - 0.0.4

**Comment by pandiaraj44** [comment]
Hi, @diegocouto,

Thanks for using the library and reporting issues, 

We will check it and let you know!

**Comment by rahulnair25283** [comment]
Hi,

I have run into the same issue. `onCancel` isn't being called from iOS.
I really like this library otherwise. It is really simple to use.

**Versions:**
react-native: v0.43.3
react-native-dialog-picker: v0.0.4

**Comment by rahulnair25283** [comment]
Hi,

I observed that in DatePickerDialog.ios.js, the `cancel()` function calls a `cancel()` function from `this.props` instead of calling the `onCancel()` function.

**Comment by pandiaraj44** [comment]
Hi @rahulnair25283, You are right we have missed that one. Thanks for your contribution and fixed it. We will move this bug fixes and and some of new features on android datepicker mode selection.
