### ISSUE TITLE
ios weird flash

### ISSUE THREAD

**Issue by neo125874** [pandiaraj44/react-native-datepicker-dialog#4]
why would the date selection flash every single rotate?

**Comment by pandiaraj44** [comment]
Hi, @neo125874 
Thanks for using our library. In which platform(android/ios) you have this issue?

**Comment by neo125874** [comment]
@pandiaraj44 ios, it seems like also happened in your screenshot?

**Comment by pandiaraj44** [comment]
@neo125874 We will check the issue and will update you.

**Comment by neo125874** [comment]
@pandiaraj44  thanks for fast response

**Comment by JulienArzul** [comment]
Hi, 
I had the same problem: on iOS, the screen was flashing (modal was removed and re-added) each time a date was selected in the picker. I submitted a pull-request that corrects it. 
Cheers.

**Comment by pandiaraj44** [comment]
Hi, @neo125874 , 

The Ios flash issue was fixed by @JulienArzul and he has raised the pull request and we have merged that pull request. 

Please install the latest version and let us know if any issues.

**Ref**
https://github.com/pandiaraj44/react-native-datepicker-dialog/pull/6
