### ISSUE TITLE
Not bring up datepicker

### ISSUE THREAD

**Issue by mad0ba** [pandiaraj44/react-native-datepicker-dialog#5]
I ran the app but when i try to select the textbox it doesn't open the datepicker. I'm using it for android.

**Comment by pandiaraj44** [comment]
Hi @Mardii-D-King ,

Have you called the date picker dialog on textbox OnPress event? 

Can you please try out our [example](https://i.diawi.com/VeCBXK) and let us know if you are facing the same issue.

**Comment by mad0ba** [comment]
So i got it to work but not like the example. When i launch the app and click in the text-box a calendar pops up instead of the scroll picker.

**Comment by mad0ba** [comment]
Nvm i got it to work also.

**Comment by pandiaraj44** [comment]
@Mardii-D-King ,

If you want the spinner date picker then you need to pass "mode" key in the options. 

The mode options were added in react-native version 42.

**Pull Request & Commit Ref**
https://github.com/facebook/react-native/pull/10932
https://github.com/facebook/react-native/commit/eaccd7e82e228d744e6aef34b332d99c1ff616a5

**Docs Ref:**
http://facebook.github.io/react-native/releases/0.42/docs/datepickerandroid.html#datepickerandroid
