### ISSUE TITLE
Warning: Failed propType: Invalid prop `data` of type `Number` supplied to `RCTDatePicker`

### ISSUE THREAD

**Issue by 12343954** [pandiaraj44/react-native-datepicker-dialog#9]
follow your tutorial，show these error，how to fix？thank you！

![image](https://user-images.githubusercontent.com/1804003/31006063-d3733aee-a4c0-11e7-8f94-0d4a564376b6.png)
![image](https://user-images.githubusercontent.com/1804003/31006076-e2f4a28c-a4c0-11e7-9312-efebdddf5000.png)

**Comment by pandiaraj44** [comment]
Hi @12343954 , Can you please post your example code here?

**Comment by pandiaraj44** [comment]
issue has been closed due to inactivity
